version: '3'
services:
  nginx:
    build:
      context: ./nginx
    depends_on:
      - php
    ports:
      - 1234:80
    volumes:
      - ./www:/var/www

  php:
    build:
      context: ./phpfpm
    volumes:
      - ./www:/var/www
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_ROOT_PASSWORD=secret
    ports:
        - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
